package backend

var stderr = struct {
	AbsPath,
	AccountNotFound,
	AuthProviderLookup,
	BuildLoginRequest,
	DecodeBase64,
	DecodeJSON,
	ECCookie,
	EncodeJSON,
	FileNotFound,
	FileOpen,
	FileWrite,
	LoginRequest,
	MakeDir,
	MaxLen,
	NoRoutes,
	ParseSignInData,
	ProviderNotFound,
	RenderFiles,
	SeeOther,
	ServiceNotFound,
	ServiceTypeMatch,
	SignOut,
	TemplateFind,
	TemplateLoad,
	TemplateParse,
	UnmarshalJSON,
	UUID,
	ValidEmail,
	WriteResponse,
	WriteResponseBody string
}{
	AbsPath:            "could not get absolute path for %v: %v",
	AccountNotFound:    "account %v not found",
	AuthProviderLookup: "cannot retrieve authentication provider: %v",
	BuildLoginRequest:  "failed to build a login request: %v",
	DecodeBase64:       "cannot decode string as base64: %v",
	DecodeJSON:         "failed to decode JSON: %v",
	ECCookie:           "cannot get the encrypted cookie: %v",
	EncodeJSON:         "cannot encode json: %v",
	FileNotFound:       "%q not found: %v",
	FileOpen:           "could not open file %v",
	FileWrite:          "could not write file %v",
	LoginRequest:       "could not login: %v",
	MakeDir:            "could not make dir: %v",
	MaxLen:             "field %v exceeds max length of %v",
	NoRoutes:           "no routes registered",
	ParseSignInData:    "could not parse login form data: %v",
	ProviderNotFound:   "OIDC provider %v was not found",
	RenderFiles:        "render files %v",
	SeeOther:           "see other %v",
	ServiceNotFound:    "service %q was not found",
	ServiceTypeMatch:   "service found at %q; type did not match any in the declared type constraint",
	SignOut:            "signing out failed: %v",
	TemplateFind:       "could not find template: %v",
	TemplateLoad:       "could not load template: %v",
	TemplateParse:      "cannot parse template: %v",
	UnmarshalJSON:      "json unmarshall error %v %v, offset: %v",
	UUID:               "cannot generate UUID: %v",
	ValidEmail:         "email failed validation: %v",
	WriteResponse:      "cannot write response: %v",
	WriteResponseBody:  "cannot write response body: %v",
}

var stdout = struct {
	CurrentVersion,
	EncryptedCookie,
	LoadGPG,
	LoadStorage,
	LoadTemplate,
	NewProfile,
	Nothing,
	PageDone,
	RequestInfo,
	RestoreSession,
	SaveStorage,
	SessionTime,
	Started,
	TemplateLoad string
}{
	CurrentVersion:  "%v, %v",
	EncryptedCookie: "looking for an encrypted cookie...",
	LoadGPG:         "loading GPG key",
	LoadStorage:     "load storage from key: %v",
	LoadTemplate:    "load template %v",
	NewProfile:      "made new profile %v",
	Nothing:         "nothing to do, bye!",
	PageDone:        "done loading page",
	RequestInfo:     "request %v %v",
	RestoreSession:  "attempting to restore previous session ID %v",
	SaveStorage:     "save storage %v",
	SessionTime:     "session time: %v",
	Started:         "handler started",
	TemplateLoad:    "loaded template: %v",
}
